version: '3.8'
services:
  mysql_container: 
    image: mysql:latest 
    container_name: mysql_container  
    restart: always
    ports:
      - "3306:3306" 
    environment:
      MYSQL_ROOT_PASSWORD: abhay  
    volumes:
      - "./mysql-data:/var/lib/mysql" 
